apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: infra-

commonLabels:
  variant: infra

commonAnnotations:
  note: Dummy-App Production Environment

resources:
  - ../../../infra
#   - argo-ingress.yaml
#   - clusterIssuer-letsencrypt-prod.yaml
#   - default_service_account.yaml

patchesStrategicMerge:
  # - cert-manager.yaml
  # - external-dns.yaml
  # - external-secrets.yml
  - loki.yaml
  # - nginx.yaml
  - prometheus-operator.yaml
  - argocd-cm.yaml
  # - kube-slack.yaml
