---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  source:
    chart: loki-stack
    helm:
      values: |
        loki:
          # persistence:
          #   enabled: true
          #   accessModes:
          #   - ReadWriteOnce
          #   size: 50Gi
          config:
            chunk_store_config:
              max_look_back_period: 360h
            table_manager:
              retention_deletes_enabled: true
              retention_period: 360h
            schema_config:
              configs:
                - from: 2020-07-01
                  store: boltdb-shipper
                  object_store: gcs
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h
            storage_config:
              gcs:
                bucket_name: production-us-loki
              boltdb_shipper:
                active_index_directory: /data/loki/boltdb-shipper-active
                shared_store: gcs
                cache_location: /data/loki/boltdb-shipper-cache
          serviceAccount:
            create: true
            # annotations:
            #   iam.gke.io/gcp-service-account: gke-node@nexite-production.iam.gserviceaccount.com

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
