---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-community
  namespace: argocd
spec:
  source:
    helm:
      values: |
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: standard
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 100Gi
        grafana:
          adminPassword: Qq121314
          sidecar:
            datasources:
              defaultDatasourceEnabled: false
            dashboards:
              enabled: true
              searchNamespace: ALL
              provider:
                foldersFromFilesStructure: true
          dashboards:
            default:
              argocd:
                url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: false
                options:
                  path: /var/lib/grafana/dashboards/default

            - name: Prometheus-loki
              type: prometheus
              url: http://loki-stack.loki.svc.cluster.local:3100/loki
              isDefault: false
            - name: Loki
              type: loki
              url: http://loki-stack.loki.svc.cluster.local:3100
              isDefault: false
              jsonData:
                maxLines: 9999
          
        coreDns:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
