apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - name: ndummy-app-helm-charts
      type: git
      url: git@github.com:liyaka/dummy-app-service.git
    - name: prometheus-community
      type: helm
      url: https://prometheus-community.github.io/helm-charts
    # - name: ingress-nginx
    #   type: helm
    #   url: https://kubernetes.github.io/ingress-nginx
    - name: external-secrets
      type: helm
      url: https://external-secrets.github.io/kubernetes-external-secrets
    - name: grafana
      type: helm
      url: https://grafana.github.io/helm-charts

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
