---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-community
  namespace: argocd
spec:
  project: nexite
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  source:
    targetRevision: 12.8.0
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
